---
# file: base.yml

- name: base play
  hosts: localhost
  gather_facts: yes
  connection: local
  tags: base

  roles:
    - role: ansiblebit.macports
      macports_upgrade_outdated: yes
      tags: macports

  tasks:
    - macports:
        name="{{ item }}"
        state=present
      become: yes
      with_items:
        - bash
        - coreutils
        - direnv
        - expect
        - git
        - parallel
      tags: macports

    - name: ensure ~/.config/git directory exists
      file:
        path="{{ ansible_env.HOME }}/.config/git/ignore.d"
        state=directory
        recurse=yes
        mode=0755

    - name: copy default system .gitignore rules
      template:
        src="{{ item }}"
        dest="{{ ansible_env.HOME }}/.config/git/ignore.d/"
        mode=0644
      with_first_found:
        - "templates/home/user/.config/git/ignore.d/ignore.{{ ansible_os_family | lower }}_{{ ansible_distribution | lower }}"
        - "templates/home/user/.config/git/ignore.d/ignore.{{ ansible_os_family | lower }}"

    - name: copy text editor / IDE .gitignore rules
      template:
        src='templates/home/user/.config/git/ignore.d/ignore.{{ item }}'
        dest="{{ ansible_env.HOME }}/.config/git/ignore.d/"
        mode=0644
      with_items:
        - jetbrains
        - textmate
        - vim

    - name: assemble gitignore rules
      assemble:
        src="{{ ansible_env.HOME }}/.config/git/ignore.d"
        dest="{{ ansible_env.HOME }}/.config/git/ignore"
        mode=0644
