---
# file: cassandra.yml

- name: cassandra play
  hosts: localhost
  gather_facts: yes
  connection: local

  tasks:
    - macports:
        name="{{ item }}"
        state=present
      sudo: yes
      with_items:
        - ccm
