---
# file: groovy.yml

- name: groovy play
  hosts: localhost
  gather_facts: yes
  connection: local

  tasks:
    - macports:
        name="{{ item }}"
        state=present
      sudo: yes
      with_items:
        - gradle
        - groovy
        - maven3
