---
# file: nodejs.yml

- name: nodejs play
  hosts: localhost
  gather_facts: yes
  connection: local

  tasks:
    - macports:
        name="{{ item }}"
        state=present
      sudo: yes
      with_items:
        - npm

    - npm:
        name={{ item }}
        global=yes
        state=present
      sudo: yes
      with_items:
        - bower
        - browser-sync
        - gulp
        - grunt
