---
# file: programming/go.yml

- name: golang play
  hosts: localhost
  gather_facts: yes
  connection: local
  vars:
    go_path: "${HOME}/go"

  tasks:
    - name: install ports
      macports:
        name="{{ item }}"
        state=present
      sudo: yes
      with_items:
        - go
        - go-tools

    - name: setup GOPATH
      file:
        path="{{ go_path }}"
        state=directory
        mode=0755 group='staff'

    - name: set file to load Go environment
      template:
        src='templates/home/user/.profile_go.j2'
        dest="{{ ansible_env.HOME }}/.profile_go"
        mode=0600 group='staff'

    - name: load Go environment on shell
      lineinfile:
        dest="{{ ansible_env.HOME }}/.profile"
        line='source ~/.profile_go'

  post_tasks:
    - name: load Go generic package dependencies
      shell: "source ~/.profile_go && go get -u {{ item }}/..."
      with_items:
        - github.com/client9/misspell/cmd/misspell
        - github.com/fzipp/gocyclo
        - github.com/golang/lint/golint
        - github.com/gordonklaus/ineffassign
        - github.com/h12w/gosweep
        - github.com/mattes/migrate
        - github.com/mattn/goveralls
        - github.com/jteeuwen/go-bindata
        - github.com/rubenv/sql-migrate
        - github.com/tools/godep
        - golang.org/x/tools/cmd/goimports
