---
# file: programming/java.yml

- name: java play
  hosts: localhost
  gather_facts: yes
  connection: local

  roles:
    - { role: oracle-java,
        oracle_java_version: 7,
        oracle_java_version_update: 80
        oracle_java_set_as_default: no }
    - { role: oracle-java,
        oracle_java_version: 8,
        oracle_java_version_update: 45
        oracle_java_set_as_default: no }

  tasks:
    - macports:
        name="{{ item }}"
        state=present
      sudo: yes
      with_items:
        - gradle
        - maven3
