---
# file: programming/ruby.yml

- name: ruby play
  hosts: localhost
  gather_facts: yes
  connection: local

  tasks:
    - macports:
        name="{{ item }}"
        state=present
      become: yes
      with_items:
        - rvm
        - autoconf
        - automake
